
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31313.79
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "makeFile", "makeFile.vcxproj", "{C6004FE2-FCB0-49E0-B934-F799790C06AF}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Debug|x64.ActiveCfg = Debug|x64
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Debug|x64.Build.0 = Debug|x64
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Debug|x86.ActiveCfg = Debug|Win32
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Debug|x86.Build.0 = Debug|Win32
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Release|x64.ActiveCfg = Release|x64
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Release|x64.Build.0 = Release|x64
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Release|x86.ActiveCfg = Release|Win32
		{C6004FE2-FCB0-49E0-B934-F799790C06AF}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {6D5FEEF7-D2C4-483D-AF8F-6989BCB5A78D}
	EndGlobalSection
EndGlobal
